### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by cifkao** [attardi/wikiextractor#1]
Trying to parse the [enwiki-20150304-pages-articles.xml.bz2](https://dumps.wikimedia.org/enwiki/20150304/enwiki-20150304-pages-articles.xml.bz2) dump causes infinite recursion:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
Traceback (most recent call last):
  File "./WikiExtractor.py", line 1708, in <module>
    main()
  File "./WikiExtractor.py", line 1704, in main
    process_data(input_file, args.templates, output_splitter)
  File "./WikiExtractor.py", line 1537, in process_data
    extract(id, title, page, output)
  File "./WikiExtractor.py", line 132, in extract
    text = clean(text)
  File "./WikiExtractor.py", line 1172, in clean
    text = expandTemplates(text)
  File "./WikiExtractor.py", line 317, in expandTemplates
    res += expandTemplate(text[s+2:e-2], frame)
  File "./WikiExtractor.py", line 730, in expandTemplate
    ret =  expandTemplates(template, frame)
  File "./WikiExtractor.py", line 317, in expandTemplates
    res += expandTemplate(text[s+2:e-2], frame)
  File "./WikiExtractor.py", line 699, in expandTemplate
    params = templateParams(parts[1:])
  File "./WikiExtractor.py", line 406, in templateParams
    parameters[i] = expandTemplates(p)
  File "./WikiExtractor.py", line 317, in expandTemplates
    res += expandTemplate(text[s+2:e-2], frame)
  File "./WikiExtractor.py", line 730, in expandTemplate
    ret =  expandTemplates(template, frame)
  File "./WikiExtractor.py", line 317, in expandTemplates
    res += expandTemplate(text[s+2:e-2], frame)
  File "./WikiExtractor.py", line 699, in expandTemplate
    params = templateParams(parts[1:])
  File "./WikiExtractor.py", line 406, in templateParams
    parameters[i] = expandTemplates(p)
  ...
  File "./WikiExtractor.py", line 317, in expandTemplates
    res += expandTemplate(text[s+2:e-2], frame)
  File "./WikiExtractor.py", line 699, in expandTemplate
    params = templateParams(parts[1:])
  File "./WikiExtractor.py", line 406, in templateParams
    parameters[i] = expandTemplates(p)
  File "./WikiExtractor.py", line 317, in expandTemplates
    res += expandTemplate(text[s+2:e-2], frame)
  File "./WikiExtractor.py", line 735, in expandTemplate
    + str(maxTemplateRecursionLevels))
  File "/usr/lib/python2.7/logging/__init__.py", line 1604, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1164, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
```

The last log entry is: `INFO:root:967	Acute disseminated encephalomyelitis`.

**Comment by attardi** [comment]
Thanks for the report.

Could you be so kind to extract that article using:

     extractPage --id 967 > 967.xml

and send it to me so that I can investigate the issue?

Thank you

-- Beppe

**Comment by jmaxx** [comment]
I have encountered the same issue with parsing the chinese wikipedia (i.e. zhwiki). I added a temporary fix in my local copy within the clean method so that I can at least continue:
```python
try:
    text = expandTemplates(text)
except RuntimeError:
    print "Runtime Error while processing text"
    text = ''
```
This is of course not elegant at all, but I haven't tracked down the source of it yet. I have noticed, however, that in this way I get loads of "Maximum recursion depth reached" messages while parsing (I rarely see actual article names actually). Does that happen in the Italian/English Wikipedia as well?

**Comment by cifkao** [comment]
@jmaxx For me, 196 pages get processed correctly, then I get 300 lines of `WARNING:root:Reached max template recursion: 16` and then the error. I didn't try your workaround, though.

**Comment by sanja7s** [comment]
The same happened to me; here is the final part of the output:

 File "WikiExtractor7s.py", line 343, in expandTemplates
    res += expandTemplate(text[s+2:e-2], frame)
  File "WikiExtractor7s.py", line 761, in expandTemplate
    + str(maxTemplateRecursionLevels))
  File "/usr/lib/python2.7/logging/__init__.py", line 1604, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1164, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
RuntimeError: maximum recursion depth exceeded

I am processing only English Wikipedia dump, 11Gb compressed. 
Thanks in advance for your help in finding the solution.

**Comment by sanja7s** [comment]
P.S.
I think that in my case it breaks for the first time when it comes to this same article:
967	Acute disseminated encephalomyelitis

**Comment by sanja7s** [comment]
And even with @jmaxx trick, it does not come to the end with processing, I get finally, after hours of processing:
 
  File "WikiExtractor7s.py", line 432, in templateParams
    parameters[i] = expandTemplates(p)
  File "WikiExtractor7s.py", line 349, in expandTemplates
    res += text[cur:]
MemoryError

This time, the code processed ~ 300K Articles
945695	313280	Canada at the 1904 Summer Olympics
945696	313281	Acanthodii

And there are 4M in total English Wikipedia.

**Comment by attardi** [comment]
It is the expansion of the template

{{Multiple sclerosis}}

in article

|967 Acute disseminated encephalomyelitis|.

that runs into a loop.
I will try to fix it.

-- Beppe

**Comment by attardi** [comment]
The reason is that the template itself is recursive.
{{Multiple sclerosis}} is defined as:

{{Navbox
| name  = Demyelinating diseases of CNS
| title = [[Multiple sclerosis]] and other [[demyelinating disease]]s of 
[[Central nervous system|CNS]] ([[ICD-10 Chapter VI: Diseases of the 
nervous system#(G35–G37) Demyelinating diseases of the central nervous 
system|G35–G37]], [[List of ICD-9 codes 320–359: diseases of the nervous 
system#Other disorders of the central nervous system (340–349)|340–341]])
|bodyclass = hlist
|{{Multiple sclerosis|state=expanded}})
...

Notice also the extra ).

-- Beppe

**Comment by jmaxx** [comment]
@sanja7s I finally finished processing of the Chinese Wikipedia Dump and did not notice any memory errors. 
@attardi Thanks Beppe! Apparently there are quite some recursive templates in Wikipedia. Did you have such issues with the Italian version as well?

**Comment by sanja7s** [comment]
thanks @jmaxx -- then you are more lucky with the Chinese Dump.

@attardi -- will you kindly notify us after the fix is implemented? thanks a lot.

Also, I see there is a multithread or parallel version in the wikiextractor code, is there some guideline how I can make the code to run that one (my computer has 8 cores and 64Gb RAM so I would like to use it maximally)?

**Comment by attardi** [comment]
On 4/7/2015 14:38, Jan wrote:
>
> @sanja7s <https://github.com/sanja7s> I finally finished processing of 
> the Chinese Wikipedia Dump and did not notice any memory errors.
> @attardi <https://github.com/attardi> Thanks Beppe! Apparently there 
> are quite some recursive templates in Wikipedia. Did you have such 
> issues with the Italian version as well?
>
Well, I had parsed the English version without problems before releasing 
the code.
The recursive template {{Multiple sclerosis}} has only appeared in a 
more recent version of the English Wikipedia.
I need to add a check for recursion in the expansion of template parameters.

-- Beppe

**Comment by attardi** [comment]
I fixed the problem. Please try it.

**Comment by cifkao** [comment]
Thanks, it works for me now.

**Comment by srepho** [comment]
Thanks so much Prof. Attardi. Really appreciate you sharing your code and providing the fix so quickly.

**Comment by sanja7s** [comment]
Thanks a lot, very helpful code, worked for me as well. And thanks for your help.
