### ISSUE TITLE
UnicodeDecodeError when parsing Chinese Wikipedia

### ISSUE THREAD

**Issue by jmaxx** [attardi/wikiextractor#11]
On parsing the Chinese Wikipedia (https://dumps.wikimedia.org/zhwiki/20150325/), I get the following error:

```
INFO: 596814	肖卡特·阿齐兹
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jan/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "WikiExtractor.py", line 2290, in run
    job.extract(self._splitter)
  File "WikiExtractor.py", line 399, in extract
    text = clean(self, text)
  File "WikiExtractor.py", line 1821, in clean
    text = extractor.expandTemplates(text)
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "WikiExtractor.py", line 671, in expandTemplate
    value = self.expandTemplates(instantiated)
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "WikiExtractor.py", line 671, in expandTemplate
    value = self.expandTemplates(instantiated)
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "WikiExtractor.py", line 606, in expandTemplate
    return self.expandTemplates(ret)
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "WikiExtractor.py", line 606, in expandTemplate
    return self.expandTemplates(ret)
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "WikiExtractor.py", line 606, in expandTemplate
    return self.expandTemplates(ret)
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "WikiExtractor.py", line 671, in expandTemplate
    value = self.expandTemplates(instantiated)
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "WikiExtractor.py", line 582, in expandTemplate
    title = self.expandTemplates(parts[0].strip())
  File "WikiExtractor.py", line 450, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 2: ordinal not in range(128)
```

The line causing the error does not explicitly invoke any ASCII decoding mechanism so I have no idea why it throws an error, but I guess there is a Chinese (or another non ASCII) character in the template. This StackOverflow question (http://stackoverflow.com/questions/21393758/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe5-in-position-0-ordinal) suggest to add
```python
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```
at the top of the document. I added the last two lines after the import lines at the top of the script and let the script run over it again (using the previously extracted templates) and it works. I also tried it without the reload command but that didn't work and I even found an explanation for that issue: http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script
So I would suggest to add 
```python
reload(sys)
sys.setdefaultencoding("utf-8")
```
to the script as it shouldn't hurt the extraction process (I can file a pull request if you like).
Thanks for your work! :)

**Comment by attardi** [comment]
Thank you for the suggestion.
I added it to the distribution.

-- Beppe

**Comment by jmaxx** [comment]
So quickly, great! That should settle the matter.

**Comment by attardi** [comment]
I found a better fix that does not involve use of deprecated setdefaultencoding.
I also made few other fixes for handling Chinese characters.

**Comment by jmaxx** [comment]
Thanks a lot for taking care of that issue! Haven't finished running it through the entire Wikipedia but up to now the output looks pretty good!
