### ISSUE TITLE
AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by talatccan** [attardi/wikiextractor#111]
C:\Users\CAN>WikiExtractor.py -cb 250k -o extracted trwiki-latest-pages-articles.xml.bz2
INFO: Loaded 0 templates in 0.0s
INFO: Starting page extraction from trwiki-latest-pages-articles.xml.bz2.
Traceback (most recent call last):
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\Scripts\WikiExtractor.py", line 4, in <module>
    __import__('pkg_resources').run_script('wikiextractor==2.69', 'WikiExtractor.py')
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 1505, in run_script
    exec(script_code, namespace, namespace)
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wikiextractor-2.69-py3.6.egg\EGG-INFO\scripts\WikiExtractor.py", line 3163, in <module>
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wikiextractor-2.69-py3.6.egg\EGG-INFO\scripts\WikiExtractor.py", line 3153, in main
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wikiextractor-2.69-py3.6.egg\EGG-INFO\scripts\WikiExtractor.py", line 2849, in process_dump
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\CAN\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'

**Comment by attardi** [comment]
You seem to be running on Windows and the error occurs in loading the multiprocessing library.
You may try using linux.

**Comment by talatccan** [comment]
I will try, thank you. :)
