### ISSUE TITLE
NameError: inside makeInternalLink

### ISSUE THREAD

**Issue by Kameegaming** [attardi/wikiextractor#13]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "wikiextractor-master/WikiExtractor.py", line 2335, in run
  File "wikiextractor-master/WikiExtractor.py", line 407, in extract
    self.magicWords['currentday'] = time.strftime('%d')
  File "wikiextractor-master/WikiExtractor.py", line 1877, in clean
    """
  File "wikiextractor-master/WikiExtractor.py", line 1486, in replaceInternalLinks
    end = m.end()
  File "wikiextractor-master/WikiExtractor.py", line 1764, in makeInternalLink
    #         # batch file existence checks for NS_FILE and NS_MEDIA
NameError: global name 'anchor' is not defined

need to rewrite:
return '<a href="%s">%s</a>' % (urllib.quote(title.encode('utf-8')), anchor) 
to:
return '<a href="%s">%s</a>' % (urllib.quote(title.encode('utf-8')), label)

**Comment by attardi** [comment]
Fixed, thank you.
