### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Kameegaming** [attardi/wikiextractor#14]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "wikiextractor-master/WikiExtractor.py", line 2355, in run
    job.extract(self._splitter)
  File "wikiextractor-master/WikiExtractor.py", line 432, in extract
    for line in compact(text):
  File "wikiextractor-master/WikiExtractor.py", line 2045, in compact
    listLevel = listLevel + n
TypeError: can only concatenate list (not "unicode") to list

changing listLevel = listLevel + n to listLevel += n fixed it for some reason

**Comment by attardi** [comment]
OK, thank you.
