### ISSUE TITLE
AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by Code4SAFrankie** [attardi/wikiextractor#140]
Getting AttributeError: module '__main__' has no attribute '__spec__' when running against the lastest af (Afrikaans) wikipedia dump using python C:\ProgramData\Anaconda3\Scripts\WikiExtractor.py --processes 1 --templates templates.fil -o Extracted afwiki-20170901-pages-meta-current.xml.bz2

INFO: Preprocessing 'afwiki-20170901-pages-meta-current.xml.bz2' to collect template definitions: this may take some time.
INFO: Saved 4773 templates to 'templates.fil'
INFO: Loaded 4773 templates in 30.4s
INFO: Starting page extraction from afwiki-20170901-pages-meta-current.xml.bz2.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\WikiExtractor.py", line 4, in <module>
    __import__('pkg_resources').run_script('wikiextractor==2.69', 'WikiExtractor.py')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1507, in run_script
    exec(script_code, namespace, namespace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wikiextractor-2.69-py3.6.egg\EGG-INFO\scripts\WikiExtractor.py", line 3238, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\wikiextractor-2.69-py3.6.egg\EGG-INFO\scripts\WikiExtractor.py", line 3228, in main
  File "C:\ProgramData\Anaconda3\lib\site-packages\wikiextractor-2.69-py3.6.egg\EGG-INFO\scripts\WikiExtractor.py", line 2923, in process_dump
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'

Running on Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by saganoren** [comment]
I`m having the same issue. What is the solution?

**Comment by samreenkazi** [comment]
hello were u able to solve this issue ?

**Comment by saganoren** [comment]
Hi!

No, I didn`t managed to solve it. I used this tool -
https://github.com/AlexBaier/wikidata_taxonomy_extraction

Best regards,
Kateryna
