### ISSUE TITLE
Another UnicodeDecodeError

### ISSUE THREAD

**Issue by Dobatymo** [attardi/wikiextractor#144]
This issue seems to be different from https://github.com/attardi/wikiextractor/issues/142
EDIT: Sorry, but it's the same as https://github.com/attardi/wikiextractor/issues/89

In my case the problem is that the default input encoding on my system is not utf-8, but the template file seems to be written as utf-8 https://github.com/attardi/wikiextractor/blob/2a5e6aebc030c936c7afd0c349e6826c4d02b871/WikiExtractor.py#L2730
So it creates the templates file with utf-8 encoding and later tries to load the file with my default system encoding which fails. Reading should explicitly specify utf-8 here as well https://github.com/attardi/wikiextractor/blob/2a5e6aebc030c936c7afd0c349e6826c4d02b871/WikiExtractor.py#L2882

```
INFO: Loading template definitions from: enwiki-20170820-pages-articles-multistream.xml.templates
Traceback (most recent call last):
  File "C:\Program Files\Python35\Scripts\WikiExtractor.py", line 4, in <module>
    __import__('pkg_resources').run_script('wikiextractor==2.69', 'WikiExtractor.py')
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources\__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources\__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "C:\Program Files\Python35\lib\site-packages\wikiextractor-2.69-py3.5.egg\EGG-INFO\scripts\WikiExtractor.py", line 3238, in <module>
  File "C:\Program Files\Python35\lib\site-packages\wikiextractor-2.69-py3.5.egg\EGG-INFO\scripts\WikiExtractor.py", line 3228, in main
  File "C:\Program Files\Python35\lib\site-packages\wikiextractor-2.69-py3.5.egg\EGG-INFO\scripts\WikiExtractor.py", line 2884, in process_dump
  File "C:\Program Files\Python35\lib\site-packages\wikiextractor-2.69-py3.5.egg\EGG-INFO\scripts\WikiExtractor.py", line 2731, in load_templates
  File "C:\Program Files\Python35\lib\site-packages\wikiextractor-2.69-py3.5.egg\EGG-INFO\scripts\WikiExtractor.py", line 2781, in pages_from
  File "C:\Program Files\Python35\lib\fileinput.py", line 248, in __next__
    line = self._readline()
  File "C:\Program Files\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7981: character maps to <undefined>
```

something like this should work
```python
def hook_compressed_encoded(filename, mode):
    encoding="utf-8"
    ext = os.path.splitext(filename)[1]
    if ext == '.gz':
        import gzip
        return gzip.open(filename, mode+"t", encoding=encoding)
    elif ext == '.bz2':
        import bz2
        return bz2.open(filename, mode+"t", encoding=encoding)
    else:
        import io
        return io.open(filename, mode, encoding=encoding)
```

and replace `openhook=fileinput.hook_compressed` with `openhook=hook_compressed_encoded`.

**Comment by ztl8702** [comment]
Same issue here. And your workaround worked for me. Thanks!

**Comment by cmills47** [comment]
Thanks for figuring this out and posting the code to fix it. Much appreciated!

**Comment by PanderMusubi** [comment]
Works indeed. thanks. Could someone create a PR for this? Will also be closing https://github.com/attardi/wikiextractor/issues/89 Hopefully @attardi  can merge it, and process some of the other waiting PRs.

**Comment by enzoftware** [comment]
That works for me. Thanks!!!!!

**Comment by Chen-0210** [comment]
Thank you! It was very helpful.
