### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by Hoainiem** [attardi/wikiextractor#154]
I have problem:
root@bt:~/Desktop/wikiextractor-master# WikiExtractor.py -c -o extracted enwikibooks-20180401-pages-articles-multistream.xml.bz2
Traceback (most recent call last):
  File "/usr/local/bin/WikiExtractor.py", line 4, in <module>
    __import__('pkg_resources').run_script('wikiextractor==2.69', 'WikiExtractor.py')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/wikiextractor-2.69-py3.6.egg/EGG-INFO/scripts/WikiExtractor.py", line 61, in <module>
  File "/usr/local/lib/python3.6/bz2.py", line 23, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

**Comment by Hoainiem** [comment]
How can i fix it?

**Comment by eracle** [comment]
What about this?
https://stackoverflow.com/questions/12806122/missing-python-bz2-module

**Comment by amproy** [comment]
I have the same problem !! WTF ! did you managed to solve it???????????????

**Comment by estelabalboa** [comment]
Not sure if this can be releated with : https://github.com/scikit-learn/scikit-learn/issues/7526 , but here gives a solution upgrading scikit-learn version.
