### ISSUE TITLE
KeyErrors intruduced by fillvalue

### ISSUE THREAD

**Issue by Kameegaming** [attardi/wikiextractor#17]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "wikiextractor-master/WikiExtractor.py", line 2355, in run
    job.extract(self._splitter)
  File "wikiextractor-master/WikiExtractor.py", line 432, in extract
    for line in compact(text):
  File "wikiextractor-master/WikiExtractor.py", line 2035, in compact
    page.append(listClose[c])
KeyError: ' '

  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "wikiextractor-master/WikiExtractor.py", line 2355, in run
    job.extract(self._splitter)
  File "wikiextractor-master/WikiExtractor.py", line 432, in extract
    for line in compact(text):
  File "wikiextractor-master/WikiExtractor.py", line 2043, in compact
    page.append(listClose[c])
KeyError: ' '

fix:
if c: to if c!=' ':

**Comment by attardi** [comment]
Then probably it is better not to use fillvalue and to check n:

                for c,n in izip_longest(listLevel, line):
                    if n and n not in '*#;:':
