### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Kameegaming** [attardi/wikiextractor#18]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "wikiextractor-master/WikiExtractor.py", line 2355, in run
    job.extract(self._splitter)
  File "wikiextractor-master/WikiExtractor.py", line 432, in extract
    for line in compact(text):
  File "wikiextractor-master/WikiExtractor.py", line 2051, in compact
    page.append(listItem[n] % line)
KeyError: u'"'

Note that line numbers are slightly higher here because of my own added code:
last line number is 2031

**Comment by attardi** [comment]
Apparently the char n is miscalculated. It should be the last of the sequence of list characters.

                n = line[i-1]   # last list char
                line = line[i:].strip()
                if line:
                    page.append(listItem[n] % line)

Can you tell me the ID of the page where this occurs?
