### ISSUE TITLE
Encoding error when extracting kab articles

### ISSUE THREAD

**Issue by MichaelKohler** [attardi/wikiextractor#199]
Originally reported here: https://github.com/Common-Voice/common-voice-wiki-scraper/issues/44. I'm sure @mozillakab is happy to answer any questions needed.

Python Version: Python 3.6.1 on Windows 7 64bit

## Error

```
C:\tal\extractwiki\wikiextractor>python WikiExtractor.py --json ../kabwiki-latest-pages-articles-multistream.xml
Traceback (most recent call last):
File "WikiExtractor.py", line 3296, in
main()
File "WikiExtractor.py", line 3282, in main
args.compress, args.processes)
File "WikiExtractor.py", line 2874, in process_dump
for line in input:
File "C:\Python36\lib\fileinput.py", line 250, in next
line = self._readline()
File "C:\Python36\lib\fileinput.py", line 364, in _readline
return self._readline()
File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 7365: cha
racter maps to 
```

```
INFO:root:16770 A?e?da
INFO:root:16771 La casa de papel
INFO:root:16772 Imendi
INFO:root:16773 Ta?e?dayt
INFO:root:16774 Idwi
INFO:root:16777 Keikob
INFO:root:16778 Tidwin
...
...
...
INFO:root:18852 Albert camus
INFO:root:18853 Ife?mes
INFO:root:18855 Suduku
INFO:root:18856 I?ed
INFO:root:18857 Awwu
INFO:root:18858 Azwu
INFO:root:18861 Ame?ruy
INFO: Finished 3-process extraction of 4509 articles in 9.3s (484.9 art/s)
INFO: total of page: 7094, total of articl page: 4509; total of used articl page
: 4509
```

## Workaround

> I replaced the content of C:\Python36\lib\encodings\cp1252.py (Western Europe) with the content of C:\Python36\lib\encodings\utf_8.py (all languages) and it works

**Comment by mozillakab** [comment]
Feel free to tag me and I can provide more info about the issue if needed.

**Comment by HjalmarrSv** [comment]
Looks like a ms win "feature". There is a fix for this as a pull request: Force 'utf-8' encoding without relying on platform-dependent default
You could try the fork of albertvillanova  to see if it helps.
I have also implemented his fix, so may other forks have.

**Comment by attardi** [comment]
Fixed in the current release.
