### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by PavelSmrz** [attardi/wikiextractor#22]
enwiki-20150515-pages-articles.xml:
INFO: 21637542  Rizzani de Eccher
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "tools/WikiExtractor.py", line 2335, in run
    job.extract(self._splitter)
  File "tools/WikiExtractor.py", line 407, in extract
    text = clean(self, text)
  File "tools/WikiExtractor.py", line 1865, in clean
    text = extractor.expandTemplates(text)
  File "tools/WikiExtractor.py", line 458, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "tools/WikiExtractor.py", line 677, in expandTemplate
    instantiated = template.subst(params, self)
  File "tools/WikiExtractor.py", line 301, in subst
    return ''.join([tpl.subst(params, extractor, depth) for tpl in self])
  File "tools/WikiExtractor.py", line 358, in subst
    res =  extractor.expandTemplates(defaultValue)
  File "tools/WikiExtractor.py", line 458, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
...
  File "tools/WikiExtractor.py", line 294, in subst
    logging.debug('subst tpl (%d, %d) %s', len(extractor.frame), depth, self)
  File "/usr/lib/python2.7/logging/__init__.py", line 1608, in debug
    root.debug(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1127, in debug
    if self.isEnabledFor(DEBUG):
  File "/usr/lib/python2.7/logging/__init__.py", line 1338, in isEnabledFor
    return level >= self.getEffectiveLevel()
RuntimeError: maximum recursion depth exceeded

**Comment by attardi** [comment]
I will take a look when I will be back.
I had no problem with that article using an earlier dump: enwiki-20150304-pages-articles.xml.bz2

**Comment by attardi** [comment]
Fixed in version 2.34.
