### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ryszard314159** [attardi/wikiextractor#23]
I encountered the problem after running WikiExtractor.py on a wiki dump for extended period of time (few days).

$ uname -a
Darwin imac.home 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
$
$ ls -l ~/Downloads/enwiki-latest-pages-articles.xml.bz2 
-rw-r-----@ 1 ryszard  501  11935745192 May 31 19:13 /Users/ryszard/Downloads/enwiki-latest-pages-articles.xml.bz
$
$ ~/util/Python/WikiExtractor.py -c -o extracted ~/Downloads/enwiki-latest-pages-articles.xml.bz2
[...]
INFO: 21637400	1976 American Airlines Tennis Games – Doubles
INFO: 21637471	Missouri River Runner
INFO: 21637508	Angelika Knipping
INFO: 21637520	List of reporters for ITV News
INFO: 21637542	Rizzani de Eccher
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/Users/ryszard/util/Python/WikiExtractor.py", line 2335, in run
    job.extract(self._splitter)
[...]
[... many lines deleted ...]
[...]
    instantiated = template.subst(params, self)
  File "/Users/ryszard/util/Python/WikiExtractor.py", line 301, in subst
    return ''.join([tpl.subst(params, extractor, depth) for tpl in self])
  File "/Users/ryszard/util/Python/WikiExtractor.py", line 351, in subst
    paramName = self.name.subst(params, extractor, depth+1)
  File "/Users/ryszard/util/Python/WikiExtractor.py", line 294, in subst
    logging.debug('subst tpl (%d, %d) %s', len(extractor.frame), depth, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1619, in debug
    root.debug(msg, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1136, in debug
    if self.isEnabledFor(DEBUG):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1348, in isEnabledFor
    return level >= self.getEffectiveLevel()
RuntimeError: maximum recursion depth exceeded

**Comment by attardi** [comment]
This problem has been fixed in version 2.34.
