### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by JonasTriki** [attardi/wikiextractor#239]
Hi there. I am trying to run the following command, but get a TypeError which stops the script from running:
```bash
python -m wikiextractor.WikiExtractor -c -b 250K -o nowiki-20200901_extracted nowiki-20200901.xml.bz2
```
I am using the 20200901 dump of the Norwegian wikipedia ([link here](https://dumps.wikimedia.org/nowiki/20200901/nowiki-20200901-pages-articles-multistream.xml.bz2)).

The error is:
```
INFO: Preprocessing 'nowiki-20200901.xml.bz2' to collect template definitions: this may take some time.
INFO: Preprocessed 100000 pages
INFO: Preprocessed 200000 pages
INFO: Preprocessed 300000 pages
INFO: Preprocessed 400000 pages
INFO: Preprocessed 500000 pages
INFO: Preprocessed 600000 pages
INFO: Preprocessed 700000 pages
INFO: Preprocessed 800000 pages
INFO: Preprocessed 900000 pages
INFO: Preprocessed 1000000 pages
INFO: Loaded 45907 templates in 135.3s
INFO: Starting page extraction from nowiki-20200901.xml.bz2.
INFO: Using 19 extract processes.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wikiextractor/WikiExtractor.py", line 480, in reduce_process
    output.write(ordering_buffer.pop(next_ordinal))
  File "/usr/local/lib/python3.6/dist-packages/wikiextractor/WikiExtractor.py", line 170, in write
    self.file.write(data)
  File "/usr/lib/python3.6/bz2.py", line 245, in write
    compressed = self._compressor.compress(data)
TypeError: a bytes-like object is required, not 'str'
```

Any idea what I am doing wrong here?

EDIT1: I used `pip install wikiextractor` to install the script.

**Comment by JonasTriki** [comment]
It seems like there was an issue with OutputSlipper.write() when `compress=True`. The fix is simply to encode the data before writing it to a `BZ2File`.
