### ISSUE TITLE
TypeError: cannot pickle '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by wengefan** [attardi/wikiextractor#246]
INFO: Starting page extraction from jawiki-latest-pages-articles.xml.bz2.
Traceback (most recent call last):
  File "C:\wikipedia\wikiextractor-master\wikiextractor\WikiExtractor.py", line 638, in <module>
    main()
  File "C:\wikipedia\wikiextractor-master\wikiextractor\WikiExtractor.py", line 633, in main
    process_dump(input_file, args.templates, output_path, file_size,
  File "C:\wikipedia\wikiextractor-master\wikiextractor\WikiExtractor.py", line 361, in process_dump
    reduce.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

C:\wikipedia\wikiextractor-master\wikiextractor>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 102, in spawn_main source_process = _winapi.OpenProcess(
    OSError: [WinError 87] パラメーターが間違っています。

**Comment by akode** [comment]
Same error on osx with python 3.8.6 wikiextractor version 3.0.4

**Comment by IlterOnatKorkmaz** [comment]
Same here with win10 python 3.9.2 wikiextractor version 3.0.4

**Comment by leanhdung1994** [comment]
Same here with win10 python 3.8.5 wikiextractor version 3.0.4.

**Comment by vtttuong** [comment]
> Same error on osx with python 3.8.6 wikiextractor version 3.0.4

can you fix it?

**Comment by BelowzeroA** [comment]
Got the same on Win10 with Python 3.7

**Comment by zhlei99** [comment]
Same error on osx with python 3.9.5

**Comment by zhujinqiu** [comment]
I fix the bug.In the source code file "WikiExtractor.py" which exists “input" of variable name.”Input“ cannot be the variable name in python3.
Substitute the "input" variable name with others and you can fix it.

**Comment by zhujinqiu** [comment]
> > Same error on osx with python 3.8.6 wikiextractor version 3.0.4
> 
> can you fix it?
I fix the bug.In the source code file "WikiExtractor.py" which exists “input" of variable name.”Input“ cannot be the variable name in python3.
Substitute the "input" variable name with others and you can fix it.

**Comment by zhujinqiu** [comment]
> > Same error on osx with python 3.8.6 wikiextractor version 3.0.4
> 
> can you fix it?

I fix the bug.In the source code file "WikiExtractor.py" which exists “input" of variable name.”Input“ cannot be the variable name in python3.
Substitute the "input" variable name with others and you can fix it.
