### ISSUE TITLE
Execution of "extractPage -v" returns this error => NameError: name 'version' is not defined

### ISSUE THREAD

**Issue by jmorenobl** [attardi/wikiextractor#258]
python -m wikiextractor.extractPage -v
Traceback (most recent call last):
  File "/Users/jorge/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jorge/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jorge/.pyenv/versions/corges/lib/python3.8/site-packages/wikiextractor/extractPage.py", line 118, in <module>
    main()
  File "/Users/jorge/.pyenv/versions/corges/lib/python3.8/site-packages/wikiextractor/extractPage.py", line 110, in main
    version='%(prog)s ' + version,
NameError: name 'version' is not defined

**Comment by jmorenobl** [comment]
I have created this fix #259
