### ISSUE TITLE
error with" global flags not at the start of the expression at position 4" help~~~

### ISSUE THREAD

**Issue by JoeyHuhuu** [attardi/wikiextractor#336]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Python\Lib\site-packages\wikiextractor\WikiExtractor.py", line 66, in <module>
    from extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "D:\Python\Lib\site-packages\wikiextractor\extract.py", line 378, in <module>
    ExtLinkBracketedRegex = re.compile(
                            ^^^^^^^^^^^
  File "D:\Python\Lib\re\__init__.py", line 228, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_parser.py", line 972, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_parser.py", line 453, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_parser.py", line 855, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_parser.py", line 453, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_parser.py", line 855, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_parser.py", line 453, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\re\_parser.py", line 833, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 4

**Comment by VladOnMyOwn** [comment]
Same here

**Comment by VladOnMyOwn** [comment]
@JoeyHuhuu, try this: https://github.com/attardi/wikiextractor/pull/313/commits/ab8988ebfa9e4557411f3d4c0f4ccda139e18875
helped me

**Comment by JoeyHuhuu** [comment]
> @JoeyHuhuu, try this: [ab8988e](https://github.com/attardi/wikiextractor/commit/ab8988ebfa9e4557411f3d4c0f4ccda139e18875) ，请尝试以下操作： [ ab8988e ](https://github.com/attardi/wikiextractor/commit/ab8988ebfa9e4557411f3d4c0f4ccda139e18875) helped me 帮助了我

thank you~

**Comment by dwiddows** [comment]
Thanks, worked for me too with python 3.12, after 
`pip uninstall wikiextractor` 
followed by 
`pip install git+https://github.com/attardi/wikiextractor.git@ab8988ebfa9e4557411f3d4c0f4ccda139e18875`

Then `python -m wikiextractor.WikiExtractor <Wikipedia xml file>` worked as before.

Thanks for this fix, it would be good if it could be merged into the pypi release. (Depends on https://github.com/attardi/wikiextractor/issues/335 I guess?)

**Comment by janarosmonaliev** [comment]
I am getting this error that setuptools aren't available. I am using the script in a conda env with Python v3.11.7
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
```

Any suggestions?

**Comment by weezymatt** [comment]
@janarosmonaliev try https://github.com/attardi/wikiextractor/commit/ab8988ebfa9e4557411f3d4c0f4ccda139e18875 and replace ```wikiextractor/extract.py``` with that file. Worked for me!

**Comment by tom9358** [comment]
I have the same problem, it would be great if the pypi version were updated!
