### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by thecerial** [attardi/wikiextractor#51]
root@f173:/home/onet/tests/chainer/wiki# wikiextractor Mozard.en
Traceback (most recent call last):
  File "/usr/local/bin/wikiextractor", line 9, in <module>
    load_entry_point('wikiextractor==2.42', 'console_scripts', 'wikiextractor')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named WikiExtractor

**Comment by attardi** [comment]
The script is called WikiExtractor.py.
You can call it directly from where you placed it.
