### ISSUE TITLE
AttributeError: type object 'Extractor' has no attribute 'keepLists'

### ISSUE THREAD

**Issue by tmkmrcnk** [attardi/wikiextractor#79]
When running the extractor on the latest dump of plwiki, the following errors are reported for each document:

INFO: Loaded 0 templates in 0.0s
INFO: Starting page extraction from data\plwiki-20160801-pages-articles.xml.bz2.
INFO: Using 23 extract processes.
ERROR:root:Processing page: 4 Alergologia
Traceback (most recent call last):
  File "C:\dev\projects\wiki\WikiExtractor.py", line 2646, in extract_process
    e.extract(out)
  File "C:\dev\projects\wiki\WikiExtractor.py", line 515, in extract
    text = compact(self.clean())
  File "C:\dev\projects\wiki\WikiExtractor.py", line 2253, in compact
    if Extractor.keepLists:
AttributeError: type object 'Extractor' has no attribute 'keepLists'
ERROR:root:Processing page: 6 ASCII
Traceback (most recent call last):
  File "C:\dev\projects\wiki\WikiExtractor.py", line 2646, in extract_process
    e.extract(out)
  File "C:\dev\projects\wiki\WikiExtractor.py", line 515, in extract
    text = compact(self.clean())
  File "C:\dev\projects\wiki\WikiExtractor.py", line 2253, in compact
    if Extractor.keepLists:
AttributeError: type object 'Extractor' has no attribute 'keepLists'
...

**Comment by attardi** [comment]
Fixed a misspelled variable in version 2.60.
