### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by agoyaliitk** [attardi/wikiextractor#8]
After article id 227107: Intellectual , got this error. I had reserved only 4gb memory for this process.

 INFO:root:227107	Intellectual
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "./WikiExtractor.py", line 1810, in run
    job.extract(self._splitter)
  File "./WikiExtractor.py", line 1782, in extract
    text = clean(text)
  File "./WikiExtractor.py", line 1334, in clean
    text = expandTemplates(text)
  File "./WikiExtractor.py", line 307, in expandTemplates
    res += wikitext[cur:s] + expandTemplate(wikitext[s+2:e-2], frame)
  File "./WikiExtractor.py", line 810, in expandTemplate
    instantiated = substParameters(template, params, frame)
  File "./WikiExtractor.py", line 857, in substParameters
    params, frame, subst_depth+1)
  File "./WikiExtractor.py", line 886, in substParameter
    parameter = expandTemplates(parameter, frame)
......................................................
......................................................
......................................................
.
.
.
.
.
 File "./WikiExtractor.py", line 545, in findBalanced
    afterPat = { o:re.compile(openPat+'|'+c, re.DOTALL) for o,c in izip(openDelim, closeDelim)}
  File "./WikiExtractor.py", line 545, in <dictcomp>
    afterPat = { o:re.compile(openPat+'|'+c, re.DOTALL) for o,c in izip(openDelim, closeDelim)}
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 232, in _compile
    p = _cache.get(cachekey)
RuntimeError: maximum recursion depth exceeded in cmp

**Comment by attardi** [comment]
Fixed in version 2.22.
