### ISSUE TITLE
unicodedecodeerror

### ISSUE THREAD

**Issue by fotisj** [attardi/wikiextractor#89]
When I am applying wikiextractor to the German wiki dump I get the following error (python 3, windows):

python wikiextractor.py dewiki-20161101-pages-meta-current2.xml-p000425451p001877043 -o wiki
Traceback (most recent call last):
  File "wikiextractor.py", line 3047, in <module>
    main()
  File "wikiextractor.py", line 3043, in main
    args.compress, args.processes)
  File "wikiextractor.py", line 2709, in process_dump
    for line in input:
  File "C:\WinPython-3.4.4\python-3.4.4.amd64\lib\fileinput.py", line 265, in __next__
    line = self.readline()
  File "C:\WinPython-3.4.4\python-3.4.4.amd64\lib\fileinput.py", line 370, in readline
    self._buffer = self._file.readlines(self._bufsize)
  File "C:\WinPython-3.4.4\python-3.4.4.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5869: character maps to <undefined>

This looks as if it is invoking the local encoding cp1252 to decode the line.

**Comment by attardi** [comment]
Must be a problem with Windows: cp1252 is the Windows character encoding.
To me on linux it works fine.

**Comment by david-leon** [comment]
Actually the problem starts at Line 2706, where the input file will be opened with system default encoding. This problem will be solved if you specify the encoding explicitly.

**Comment by attardi** [comment]
How do you specify the encoding to FileInput()?

**Comment by david-leon** [comment]
@attardi : yes you are right, I replaced the FileInput() with open(), and removed a few lines with decoding('utf8')

**Comment by cswef** [comment]
Python 3,Windows

Error:
Traceback (most recent call last):
  File "D:\***\wikiextractor-master-20170105\WikiExtractor.py",
line 3046, in <module>
    main()
  File "D:\***\wikiextractor-master-20170105\WikiExtractor.py",
line 3042, in main
    args.compress, args.processes)
  File "D:\***\wikiextractor-master-20170105\WikiExtractor.py",
line 2708, in process_dump
    for line in input:
  File "D:\Program Files (x86)\***\Python35\lib\fileinput.py", line 248, in __next__
    line = self._readline()
  File "D:\Program Files (x86)\***\Python35\lib\fileinput.py", line 362, in _readline
    return self._readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 6209: illegal multibyte sequence
------------------------------------------------------------------

Solution:
According to :
https://github.com/rappdw/wikiextractor/commit/934688f8f936ffae756c7f7bd072df1df22dd554

Line 2706:
-        input = fileinput.FileInput(input_file, openhook=fileinput.hook_compressed)
+        input = open(input_file, 'r', encoding='utf-8')

Line 2710:
-        line = line.decode('utf-8')

**Comment by marsel365** [comment]
Удалить:
input = fileinput.FileInput (input_file, openhook = fileinput.hook_compressed)
Добавить:
input = fileinput.FileInput(input_file, openhook=fileinput.hook_encoded("utf-8"))
